/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fictitious_money_purse_utils_XMHCoinUtitls */

#ifndef _Included_com_fictitious_money_purse_utils_XMHCoinUtitls
#define _Included_com_fictitious_money_purse_utils_XMHCoinUtitls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_generateMnemonicIndex
 * Signature: ([BB[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1generateMnemonicIndex
  (JNIEnv *, jclass, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_SetMaster
 * Signature: ([BS)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1SetMaster
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveEOSKeyRoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveEOSKeyRoot
  (JNIEnv *, jclass);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveEOSKeyAccount
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveEOSKeyAccount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveEOSKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveEOSKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ECDSA_sign
 * Signature: ([BI[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ECDSA_1sign
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportEOSPubKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportEOSPubKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportEOSPrvKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportEOSPrvKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportEOSPrvKeyCheck
 * Signature: ([BB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportEOSPrvKeyCheck
  (JNIEnv *, jclass, jbyteArray, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportEOSPrvKey
 * Signature: ([BB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportEOSPrvKey
  (JNIEnv *, jclass, jbyteArray, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_GetTranSigJson
 * Signature: ([BS[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1GetTranSigJson
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_EncKeyByAES128CBC
 * Signature: ([BS[BB[B[BB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1EncKeyByAES128CBC
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jbyte, jbyteArray, jbyteArray, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DecKeyByAES128CBC
 * Signature: ([BS[BB[B[BB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DecKeyByAES128CBC
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jbyte, jbyteArray, jbyteArray, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveETHKeyRoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveETHKeyRoot
  (JNIEnv *, jclass);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveETHKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveETHKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveETHKeyAccount
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveETHKeyAccount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportETHPubKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportETHPubKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigtEthTransaction
 * Signature: ([BS[BS[BS[B[BS[BS[BS[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigtEthTransaction
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jshort, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getMasterPubKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getMasterPubKey
  (JNIEnv *, jclass);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeTranJSON
 * Signature: ([BS[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeTranJSON
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packTranJson
 * Signature: ([B[BIS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packTranJson
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genBTCAddress
 * Signature: (B[BBB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genBTCAddress
  (JNIEnv *, jclass, jbyte, jbyteArray, jbyte, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigtBTCTransaction
 * Signature: ([BS[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigtBTCTransaction
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportETHPrvKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportETHPrvKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveBTCKeyRoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveBTCKeyRoot
  (JNIEnv *, jclass);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveBTCKeyAccount
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveBTCKeyAccount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveBTCKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveBTCKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportBTCPrvKeyByWIF
 * Signature: ([BS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportBTCPrvKeyByWIF
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportBTCPrvKeyByWIF
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportBTCPrvKeyByWIF
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genScriptHash
 * Signature: ([BS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genScriptHash
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeETHTranJSON
 * Signature: ([BS[BS[BS[B[BS[BS[BS[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeETHTranJSON
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jshort, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packETHTranJson
 * Signature: ([B[BI[BS[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packETHTranJson
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray, jshort, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBTCTranJSON
 * Signature: ([BS[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBTCTranJSON
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBTCTranJson
 * Signature: (B[BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBTCTranJson
  (JNIEnv *, jclass, jbyte, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkMemoValid
 * Signature: ([SB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkMemoValid
  (JNIEnv *, jclass, jshortArray, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genTrueRandom
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genTrueRandom
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_authValidAPP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1authValidAPP
  (JNIEnv *, jclass, jobject);


/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_EncByAES128CBC
 * Signature: ([BS[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1EncByAES128CBC
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DecByAES128CBC
 * Signature: ([BS[B[B)S
 */
JNIEXPORT jshort JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DecByAES128CBC
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genKeyPair
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genKeyPair
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_keyAgreement
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1keyAgreement
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ECDSA_verify
 * Signature: ([BI[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ECDSA_1verify
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveKeyRoot
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveKeyRoot
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveKeyAccount
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveKeyAccount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBYTOMAddress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBYTOMAddress
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigtBYTOMTransaction
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigtBYTOMTransaction
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBYTOMTranJSON
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBYTOMTranJSON
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBYTOMTranJson
 * Signature: ([BS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBYTOMTranJson
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_importKeyStore
 * Signature: ([B[BB[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1importKeyStore
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_exportKeyStore
 * Signature: ([BBB[BB[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1exportKeyStore
  (JNIEnv *, jclass, jbyteArray, jbyte, jbyte, jbyteArray, jbyte, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBYTOMCode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBYTOMCode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportBYTOMPrvKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportBYTOMPrvKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeTranJSONOnly
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeTranJSONOnly
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packTranJsonOnly
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packTranJsonOnly
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBTCTranJSONOnly
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBTCTranJSONOnly
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBTCTranJsonOnly
 * Signature: ([BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBTCTranJsonOnly
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBYTOMTranJSONOnly
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBYTOMTranJSONOnly
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBYTOMTranJsonOnly
 * Signature: ([BS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBYTOMTranJsonOnly
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportPrvKeyByWIF
 * Signature: ([BS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportPrvKeyByWIF
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportPrvKeyByWIF
 * Signature: (B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportPrvKeyByWIF
  (JNIEnv *, jclass, jbyte, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBCHAddress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBCHAddress
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigETH_TX_by_str
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigETH_1TX_1by_1str
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serETH_TX_by_str
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serETH_1TX_1by_1str
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jbyteArray);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packETH_TX_by_str
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packETH_1TX_1by_1str
  (JNIEnv *, jclass, jstring, jstring, jint, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkETHpushValid
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkETHpushValid
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jboolean, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_SetMasterStandard
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1SetMasterStandard
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_deriveKeyByPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1deriveKeyByPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_GetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkEOSpushValid
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkEOSpushValid
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkBTCpushValid
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkBTCpushValid
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkBYTOMpushValid
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkBYTOMpushValid
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_SHA256
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1SHA256
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkAddressValid
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkAddressValid
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_checkCrossChain
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1checkCrossChain
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_EncPhoneNum
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1EncPhoneNum
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DecPhoneNum
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DecPhoneNum
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportEOSPubByPre
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportEOSPubByPre
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_cvtAddrByEIP55
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1cvtAddrByEIP55
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveEOSKeyStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveEOSKeyStr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveETHKeyStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveETHKeyStr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportEOSPubKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportEOSPubKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportEOSPrvKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportEOSPrvKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ParseEOSPubKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ParseEOSPubKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportEOSPrvKeyCheckStr
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportEOSPrvKeyCheckStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportEOSPrvKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportEOSPrvKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_GetTranSigJsonStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1GetTranSigJsonStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportETHPubKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportETHPubKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getMasterPubKeyStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getMasterPubKeyStr
  (JNIEnv *, jclass);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeTranJSONStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeTranJSONStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packTranJsonStr
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packTranJsonStr
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genBTCAddressStr
 * Signature: (BLjava/lang/String;B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genBTCAddressStr
  (JNIEnv *, jclass, jbyte, jstring, jbyte);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigtBTCTransactionStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigtBTCTransactionStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportETHPrvKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportETHPrvKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveBTCKeyStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveBTCKeyStr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportBTCPrvKeyByWIFStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportBTCPrvKeyByWIFStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportBTCPrvKeyByWIFStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportBTCPrvKeyByWIFStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genScriptHashStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genScriptHashStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBTCTranJSONStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBTCTranJSONStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBTCTranJsonStr
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBTCTranJsonStr
  (JNIEnv *, jclass, jboolean, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_DeriveKeyStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1DeriveKeyStr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBYTOMAddressStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBYTOMAddressStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigtBYTOMTransactionStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigtBYTOMTransactionStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBYTOMTranJSONStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBYTOMTranJSONStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBYTOMTranJsonStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBYTOMTranJsonStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_importKeyStoreStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1importKeyStoreStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_exportKeyStoreStr
 * Signature: (Ljava/lang/String;BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1exportKeyStoreStr
  (JNIEnv *, jclass, jstring, jbyte, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBYTOMCodeStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBYTOMCodeStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportBYTOMPrvKeyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportBYTOMPrvKeyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeTranJSONOnlyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeTranJSONOnlyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packTranJsonOnlyStr
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packTranJsonOnlyStr
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBTCTranJSONOnlyStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBTCTranJSONOnlyStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBTCTranJsonOnlyStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBTCTranJsonOnlyStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serializeBYTOMTranJSONOnlyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serializeBYTOMTranJSONOnlyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBYTOMTranJsonOnlyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBYTOMTranJsonOnlyStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ImportPrvKeyByWIFStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ImportPrvKeyByWIFStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_ExportPrvKeyByWIFStr
 * Signature: (BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1ExportPrvKeyByWIFStr
  (JNIEnv *, jclass, jbyte, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBCHAddressStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBCHAddressStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBTMMultSigInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBTMMultSigInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_createBTMMultAddr
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1createBTMMultAddr
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBTMMultSigInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBTMMultSigInfo
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBTMMultSigSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBTMMultSigSignature
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_BTMMSSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1BTMMSSignature
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_BTMMSVerify
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1BTMMSVerify
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBTCMultSigInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBTCMultSigInfo
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_createBTCMultAddr
 * Signature: (BLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1createBTCMultAddr
  (JNIEnv *, jclass, jbyte, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_packBTCMultSigInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1packBTCMultSigInfo
  (JNIEnv *, jclass, jstring, jstring, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getBTCMultSigSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getBTCMultSigSignature
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_BTCMSSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1BTCMSSignature
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_BTCMSVerify
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1BTCMSVerify
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serBTMMS
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serBTMMS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_serBTCMS
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1serBTCMS
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_filterUTXO
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1filterUTXO
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jint, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getXMRAddress
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getXMRAddress
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getXMRViewBySpend
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getXMRViewBySpend
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getXMRPubByPrv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getXMRPubByPrv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigtMoneroTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigtMoneroTransaction
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_searchXMRTX
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1searchXMRTX
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_CRC16_CCITT_FALSE
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1CRC16_1CCITT_1FALSE
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_genPolkaDotKeyPairByPath
 * Signature: ([SILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1genPolkaDotKeyPairByPath
  (JNIEnv *, jclass, jshortArray, jint, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getPolkaDotAddress
 * Signature: (BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getPolkaDotAddress
  (JNIEnv *, jclass, jbyte, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_sigPolkadotTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1sigPolkadotTransaction
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_polkadot_ept_keystore
 * Signature: (Ljava/lang/String;Ljava/lang/String;BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1polkadot_1ept_1keystore
  (JNIEnv *, jclass, jstring, jstring, jbyte, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_polkadot_ipt_keystore
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1polkadot_1ipt_1keystore
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_getPolkaPubByPriv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1getPolkaPubByPriv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fictitious_money_purse_utils_XMHCoinUtitls
 * Method:    CoinID_polkadot_getNonceKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fictitious_money_purse_utils_XMHCoinUtitls_CoinID_1polkadot_1getNonceKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
